### ISSUE TITLE
[STS] Add sort by root domain

### ISSUE THREAD

**Issue by correcthorsebatterystaple** [pwhite2/simple-tab-sorter#20]
**Is your feature request related to a problem? Please describe.**
I would love to have the ability to sort the tabs by the root domain name. It would work by first sorting by the root domain and then by the subdomain.

**Describe the solution you'd like**
It could be an addition value in the sort by drop down in the settings. When selected it does a two part sort first sorts by the root domain and then by the subdomain and then maybe by the path. So something like 
```
[sheets.google.com, reddit.com, books.google.com, old.reddit.com]
``` 
would be sorted to 
```
[books.google.com, sheets.google.com, reddit.com, old.reddit.com]
```  

**Describe alternatives you've considered**
None really, Big fan of this extension being open source would love to keep using it.

**Additional context**

**Comment by pwhite2** [comment]
Hi @correcthorsebatterystaple. Sorry it took so long, but I implemented your request in [Super Tab Sorter](https://github.com/pwhite2/super-tab-sorter) and just published it on the Chrome Web Store.

The new extension isn't appearing in the web store search yet, but [this](https://chromewebstore.google.com/detail/super-tab-sorter/jjhppbooocacaccnhjninhmigbfmpnkh) is its direct link.
