### ISSUE TITLE
[BUG] Chrome's new suspended tabs breaks this plugin

### ISSUE THREAD

**Issue by beaugunderson** [pwhite2/simple-tab-sorter#21]
For suspended tabs the tab object's `url` attribute will be an empty string while `pendingUrl` will contain the suspended URL, so this plugin should update to check for `pendingUrl` and use that if it's not empty.

**Comment by pwhite2** [comment]
Hi @beaugunderson, thanks for reporting the issue and submitting a PR - I haven't had the time to keep up with the changes to chrome for a while and really appreciate you providing a solution along with the bug report. The PR looks good, so I'll merge it and submit an update to the chrome web store.

**Comment by beaugunderson** [comment]
fantastic, thanks for doing that! I’ve been using it and it’s been working
:)
