### ISSUE TITLE
[STS] Don't Sort Groups By Name

### ISSUE THREAD

**Issue by WHiZSTA** [pwhite2/simple-tab-sorter#26]
Currently the sort works great on the webpages, but it also inadvertently sorts my groups by name alphabetically, when i like many people, already have our groups ordered as we want them. This basically overrides my group order when i want to sort the items inside them. Can we please get an option to enable/disable the group name sorting.

Thanks for the great extension!

**Comment by pwhite2** [comment]
Hi @WHiZSTA,

You can preserve any desired tab group order by naming your tab groups with a numeric prefix, as documented in the user guide, which will result in your tab groups being ordered by their numeric prefix.

This is the best I can do at the moment - if you review the properties at https://developer.chrome.com/docs/extensions/reference/api/tabGroups#type-TabGroup, you'll note that `windowId` is `TabGroup`'s only position-related property, leaving me nothing else to work with.

Best,
Peter
